[workspace]
authors = ["Tim Treis <tim.treis@helmholtz-munich.de>"]
channels = ["conda-forge"]
name = "2023_Arevalo_BatchCorrection"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.10.*"
conda = "*"

[pypi-dependencies]
snakemake = ">=7,<8"
pulp = ">=2.7,<2.8" # needed for "list_solvers = listSolvers" alias
anndata = "*"
scanpy = ">=1.11.4, <2"
pyarrow = "*"
scib-metrics = "*"
scikit-learn = "*"
copairs = "*"
tqdm = "*"
statsmodels = "*"
scipy = "*"
pycytominer = "*"
matplotlib = "*"
plotly = "*"
seaborn = "*"

[tasks]
pipeline = "PATH=$(dirname $(which python)):$PATH snakemake -c20 --configfile inputs/conf/scenario_7.json --use-conda --conda-prefix './env_store/' --conda-frontend conda --resources nvidia_gpu=2"
unlock = "PATH=$(dirname $(which python)):$PATH snakemake -c20 --configfile inputs/conf/scenario_7.json --use-conda --conda-prefix './env_store/' --conda-frontend conda --resources nvidia_gpu=2 --unlock"
